[workspace]
resolver = "2"
members = ["uggo", "ugg-proxy", "ugg-proxy-cf", "ugg-types"]

[profile.release]
opt-level = 3
strip = true

[patch.crates-io]
reflink = { git = "https://github.com/nicokoch/reflink.git" }
