[package]
name = "uggo"
version = "0.4.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking", "json"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
lazy_static = "1.4.0"
colored = "2.0.0"
chrono = "0.4.19"
text_io = "0.1.9"
ctrlc = "3.2.0"
strum = "0.21"
strum_macros = "0.21"
levenshtein = "1.0.5"
prettytable-rs = "0.8.0"

[profile.release]
opt-level = "z"