[workspace]
resolver = "2"
members = [
    "crates/uggo",
    "crates/ugg-types",
    "crates/ugg-api",
    "crates/config",
    "crates/lol-client"
]

[profile.release]
opt-level = 3
strip = true
codegen-units = 1
lto = true

[profile.release-small]
inherits = "release"
opt-level = "z"