# fly.toml file generated for ugg-proxy on 2023-01-10T17:26:38-05:00

app = "ugg-proxy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
BIND_ADDRESS = "0.0.0.0"
BIND_PORT = "3000"
LOG_LEVEL = "info"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
