[package]
name = "uggo-lol-client"
version = "0.3.0"
edition = "2021"
rust-version = "1.80"
license = "MIT"
description = "uggo dependency -- API bindings for the League of Legends client"
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../../README.md"
keywords = ["uggo"]
categories = ["api-bindings"]

[lints]
workspace = true

[dependencies]
league-client-connector = "0.1.2"
native-tls = "0.2.11"
serde = "1.0.200"
thiserror = "2.0.0"
ureq = { version = "3.0.0", features = ["native-tls", "brotli", "json"] }
ugg-types = { version = "0.6.0", path = "../ugg-types" }
