[package]
name = "uggo-lol-client"
version = "0.2.2"
edition = "2021"
rust-version = "1.74"
license = "MIT"
description = "uggo dependency -- API bindings for the League of Legends client"
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../../README.md"
keywords = ["uggo"]
categories = ["api-bindings"]

[dependencies]
league-client-connector = "0.1.2"
native-tls = "0.2.11"
serde = "1.0.199"
thiserror = "1.0.59"
ureq = { version = "2.9.7", features = ["native-tls", "brotli", "json"] }
ugg-types = { version = "0.5.2", path = "../ugg-types" }
