[package]
name = "uggo-lol-client"
version = "0.2.1"
edition = "2021"
rust-version = "1.74"
license = "MIT"
description = "uggo dependency -- API bindings for the League of Legends client"
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../../README.md"
keywords = ["uggo"]
categories = ["api-bindings"]

[dependencies]
league-client-connector = "0.1.2"
native-tls = "0.2.11"
serde = "1.0.195"
thiserror = "1.0.56"
http = "1.0.0"
ureq = { version = "2.9.1", features = ["native-tls", "brotli", "json"] }
ugg-types = { version = "0.5.1", path = "../ugg-types" }
wamp_async = { version = "0.3.1", optional = true }
tokio = { version = "1.36.0", optional = true }
futures-util = "0.3.30"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls"], optional = true }


[features]
async = ["wamp_async", "tokio", "tokio-tungstenite"]

[dev-dependencies]
tokio-test = "0.4.3"
env_logger = "0.11.1"
