[package]
name = "uggo-lol-client"
version = "0.1.0"
edition = "2021"
rust-version = "1.68.2"
license = "MIT"
description = "CLI tool to query builds from u.gg, for League of Legends."
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../README.md"
keywords = ["ugg", "league", "of", "legends"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
league-client-connector = "0.1.2"
native-tls = "0.2.11"
serde = "1.0.192"
sha2 = "0.10.8"
thiserror = "1.0.50"
ureq = { version = "2.8.0", features = ["native-tls", "brotli"] }
ugg-types = { version = "0.3.0", path = "../ugg-types" }