[package]
name = "uggo-ugg-api"
version = "0.2.2"
edition = "2021"
rust-version = "1.74"
license = "MIT"
description = "uggo dependency -- API client for u.gg"
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../../README.md"
keywords = ["uggo"]
categories = ["api-bindings"]

[dependencies]
ddragon = { workspace = true }
hex = "0.4.3"
levenshtein = "1.0.5"
lru = "0.12.3"
native-tls = { workspace = true }
serde = { workspace = true }
simd-json = { version = "0.13.9", default-features = false, features = ["serde_impl", "swar-number-parsing"] }
sha2 = "0.10.8"
thiserror = { workspace = true }
ureq = { workspace = true }
ugg-types = { version = "0.5.2", path = "../ugg-types" }

[features]
json-runtime-detection = ["simd-json/runtime-detection"]
default = ["json-runtime-detection"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{version}-{ target }{ archive-suffix }"
pkg-fmt = "bin"
