[package]
name = "uggo-ugg-api"
version = "0.1.1"
edition = "2021"
rust-version = "1.74"
license = "MIT"
description = "uggo dependency -- API client for u.gg"
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../../README.md"
keywords = ["uggo"]
categories = ["api-bindings"]

[dependencies]
ddragon = "0.8.1"
hex = "0.4.3"
levenshtein = "1.0.5"
lru = "0.12.1"
native-tls = "0.2.11"
serde = "1.0.193"
simd-json = { version = "0.13.4", default-features = false, features = ["serde_impl", "swar-number-parsing"] }
sha2 = "0.10.8"
thiserror = "1.0.50"
ureq = { version = "2.9.0", features = ["native-tls", "brotli"] }
ugg-types = { version = "0.4.1", path = "../ugg-types" }

[features]
json-runtime-detection = ["simd-json/runtime-detection"]
default = ["json-runtime-detection"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{version}-{ target }{ archive-suffix }"
pkg-fmt = "bin"
