[package]
name = "uggo"
version = "0.10.1"
edition = "2021"
rust-version = "1.68.2"
license = "MIT"
description = "CLI tool to query builds from u.gg, for League of Legends."
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
readme = "../README.md"
keywords = ["ugg", "league", "of", "legends"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bpaf = { version = "0.9.6", features = ["derive"] }
colored = "2.0.4"
ddragon = "0.8.1"
hex = "0.4.3"
league-client-connector = "0.1.2"
levenshtein = "1.0.5"
lru = "0.12.0"
mimalloc = "0.1.39"
native-tls = "0.2.11"
prettytable-rs = "0.10.0"
serde = "1.0.192"
simd-json = { version = "0.13.4", default-features = false, features = ["serde_impl", "swar-number-parsing"] }
sha2 = "0.10.8"
text_io = "0.1.12"
time = { version = "0.3.30", features = ["local-offset", "formatting", "macros"] }
ureq = { version = "2.8.0", features = ["native-tls", "brotli"] }
ugg-types = { version = "0.3.0", path = "../ugg-types" }
uggo-config = { version = "0.1.0", path = "../config" }
uggo-lol-client = { version = "0.1.0", path = "../lol-client" }
uggo-ugg-api = { version = "0.1.0", path = "../ugg-api" }

[features]
json-runtime-detection = ["simd-json/runtime-detection"]
default = ["json-runtime-detection"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{version}-{ target }{ archive-suffix }"
pkg-fmt = "bin"
