[package]
name = "ugg-types"
version = "0.3.0"
edition = "2021"
license = "MIT"
rust-version = "1.74"
description = "Types for the uggo CLI tool and ugg-proxy server."
homepage = "https://github.com/kade-robertson/uggo"
repository = "https://github.com/kade-robertson/uggo"
keywords = ["ugg", "league", "of", "legends"]

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }