on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 3 * * 1'

name: build-caches
jobs:
  test:
    name: build rust caches
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'rust'
          shared-key: 'cache'

      - name: Build cache
        run: |
          cargo check --quiet
          cargo test --quiet
          cargo build --quiet
          cargo check --quiet --release
          cargo build --quiet --release