on:
  push:
    branches: [master]
  schedule:
    - cron: "30 3 * * 1"

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

name: build-caches
jobs:
  test:
    name: build rust caches
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        toolchain: [1.80.1, stable]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Build cache
        run: |
          cargo test --locked
          cargo build --locked
