on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 3 * * 1'

name: build-caches
jobs:
  test:
    name: build rust caches
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build cache
        run: |
          cargo check --quiet
          cargo test --quiet
          cargo check --quiet --release
          cargo build --quiet --release

      - name: Cargo cache
        uses: actions/cache/save@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}
          enableCrossOsArchive: true