on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 3 * * 1'

name: build-caches
jobs:
  test:
    name: build rust caches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Test (to build cache)
        run: cargo test