on:
  pull_request:
    branches: [master]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

name: test
jobs:
  test:
    name: test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - id: toolchain
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.68.2
        with:
          components: clippy

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Test uggo
        run: cargo test --locked --package uggo

      - name: Build uggo
        run: cargo build --locked --package uggo --release

      - name: Test ugg-types and ugg-proxy
        if: runner.os == 'Linux'
        run: |
          cargo test --locked --package ugg-types
          cargo test --locked --package ugg-proxy

      - name: Build ugg-types and ugg-proxy
        if: runner.os == 'Linux'
        run: |
          cargo build --locked --package ugg-types --release
          cargo build --locked --package ugg-proxy --release
