on:
  pull_request:
    branches: [master]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

name: test
jobs:
  test:
    name: test
    strategy:
      matrix:
        toolchain: [1.85.0, stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - id: toolchain
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Test
        run: cargo test --locked

      - name: Build
        run: cargo build --locked
