on:
  pull_request:
    branches: [ master ]

name: test
jobs:
  test:
    name: test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'rust'
          shared-key: 'cache'

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release
