on:
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

name: test
jobs:
  test:
    name: test (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Test uggo
        run: cargo test --package uggo

      - name: Build uggo
        run: cargo build --package uggo --release

      - name: Test ugg-types and ugg-proxy
        if: runner.os == 'Linux'
        run: |
          cargo test --package ugg-types
          cargo test --package ugg-proxy

      - name: Build ugg-types and ugg-proxy
        if: runner.os == 'Linux'
        run: |
          cargo build --package ugg-types --release
          cargo build --package ugg-proxy --release
